/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_mkr_dbw_modules_NativeExcelModule */

#ifndef _Included_ru_mkr_dbw_modules_NativeExcelModule
#define _Included_ru_mkr_dbw_modules_NativeExcelModule
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     ru_mkr_dbw_modules_NativeExcelModule
	 * Method:    _setExceptionHandlingEnabled
	 * Signature: (Z)Z
	 */
	JNIEXPORT jboolean JNICALL Java_ru_mkr_dbw_modules_NativeExcelModule__1setExceptionHandlingEnabled
	(JNIEnv*, jobject, jboolean);

	/*
	 * Class:     ru_mkr_dbw_modules_NativeExcelModule
	 * Method:    _readExcelBook
	 * Signature: (Ljava/lang/String;Ljava/util/Map;Ljava/util/List;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_ru_mkr_dbw_modules_NativeExcelModule__1readExcelBook
	(JNIEnv*, jobject, jint, jstring, jobject, jobjectArray, jboolean);

	/*
	 * Class:     ru_mkr_dbw_modules_NativeExcelModule
	 * Method:    _writeCell
	 * Signature: (ILjava/lang/String;IILjava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_ru_mkr_dbw_modules_NativeExcelModule__1writeCell
	(JNIEnv*, jobject, jint, jstring, jint, jint, jstring);

	/*
	 * Class:     ru_mkr_dbw_modules_NativeExcelModule
	 * Method:    _saveBook
	 * Signature: (ILjava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_ru_mkr_dbw_modules_NativeExcelModule__1saveBook
	(JNIEnv*, jobject, jint, jstring);

	/*
	 * Class:     ru_mkr_dbw_modules_NativeExcelModule
	 * Method:    _closeBook
	 * Signature: (I)Z
	 */
	JNIEXPORT jboolean JNICALL Java_ru_mkr_dbw_modules_NativeExcelModule__1closeBook
	(JNIEnv*, jobject, jint);

	/*
	 * Class:     ru_mkr_dbw_modules_NativeExcelModule
	 * Method:    _dispose
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_ru_mkr_dbw_modules_NativeExcelModule__1dispose
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
